import { generatorHandler } from "@prisma/generator-helper";
import fs from "node:fs/promises";
import path from "node:path";

const header = `// This file was generated by a custom prisma generator, do not edit manually.
// Workaround for Prisma 7 mapped enum bug (https://github.com/prisma/prisma/issues/28591)
// Generates enums with KEY as value (Prisma 6 style) instead of mapped value.
`;

generatorHandler({
  onManifest() {
    return {
      defaultOutput: "./enums/index.ts",
      prettyName: "Prisma Enum Generator",
    };
  },
  async onGenerate(options) {
    const enums = options.dmmf.datamodel.enums;

    // Generate enums with KEY as value (Prisma 6 behavior)
    // This fixes the Prisma 7 bug where runtime expects KEY but types have mapped value
    const enumCode = enums
      .map((enumDef) => {
        const values = enumDef.values
          .map((v) => `  ${v.name}: '${v.name}'`)
          .join(",\n");
        return `export const ${enumDef.name} = {\n${values}\n} as const\n\nexport type ${enumDef.name} = (typeof ${enumDef.name})[keyof typeof ${enumDef.name}]\n`;
      })
      .join("\n");

    const outputFile = options.generator.output;
    if (!outputFile || !outputFile.value) {
      throw new Error("No output file specified");
    }

    const outputPath = path.resolve(outputFile.value);
    await fs.mkdir(path.dirname(outputPath), { recursive: true });
    await fs.writeFile(outputPath, header + enumCode, "utf-8");
  },
});
